

//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//        By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


public class Task2 {
    public static void main(String[] args) {
        int i = 1;
        int j = 2;
        int m = 0;
        int summa_fib = 2;
        int summa_check = 0;

        while (true) {
            m = i + j;
            if ( m%2 == 0){
                summa_check = summa_fib + m;
                if (summa_check < 4000000) summa_fib+=m;
                else break;
            }
            i = j;
            j = m;
        }

        System.out.println(summa_fib);
    }
}
